### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by IgorGanapolsky** [JorgeCastilloPrz/Dagger2Scopes#4]
I cannot build your project.  I get the  following error:

> Error:Execution failed for task ':android:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 1

Please help.

**Comment by ppamorim** [comment]
Go to "Project Structure" > "SDK Location" > "JDK location" and change to 1.7

**Comment by IgorGanapolsky** [comment]
Nope, no dice.  And besides, I like using 1.8 for RxJava and Lambdas.

**Comment by ppamorim** [comment]
Good lucky.

**Comment by JorgeCastilloPrz** [comment]
Hi! I am sorry, but as i told in @ppamorim issue, i never used Java 8 as it is not really compatible with Android and i never used retrolambda. I know retrolambda + Rx is really cool, but i am not used to work with the two of them. If you can find a solution i would love to know about it, because it might be a Dagger problem working with java8 or something, and people deserves to know :)

**Comment by IgorGanapolsky** [comment]
@JorgeCastilloPrz  I think the main issue is that your sample project is not aimed at being an Android application.  You have things like `apply plugin: 'war'`, which is for web applications only!

**Comment by JorgeCastilloPrz** [comment]
That is not true. The module called "android" is the only one depending on Android SDK, and it has correct plugins. It is marked as an android application and build.gradle specifies all the android configuration there (applicationId, minSdkVersion, targetSdkVersion, compileSdkVersion, buildToolsVersion... etc.

 It is compiling without any trouble with Android SDK and Java 1.7.

**Comment by JorgeCastilloPrz** [comment]
But there could be a problem. @ppamorim added the following lines to android module build.gradle:
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_7
    targetCompatibility JavaVersion.VERSION_1_7
}
That might be the problem. May be you should change it to 1.8 or remove them in order to make it work with Java 8?

Here is the pull request: https://github.com/JorgeCastilloPrz/Dagger2Scopes/pull/3

**Comment by IgorGanapolsky** [comment]
I already added
`compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }`
in android module's **build.gradle**.  No dice.

**Comment by JorgeCastilloPrz** [comment]
So, it seems that you know more than me about Java 8. If you come up with a solution, please, let me know!. I am pretty sure it has to be a simple thing when you find it.
